enum SUPPORTED_READINGS {
  NHK_NEWS_WEB_EASY
}

type Question {
  question: String!
  answer: String!
  discussion_questions: [Reading]! @relation(name: "discussion_questions")
}

type Vocabulary {
  word: String!
  definition: String
  discussion_questions: [Reading]! @relation(name: "discussion_vocab")
}

type Reading {
  discussion_questions: [Question]! @relation(name: "discussion_questions")
  vocab: [Vocabulary]! @relation(name: "discussion_vocab")
  reading_type: SUPPORTED_READINGS!
  reading_url: String!
  text: String!
  title: String!
  teachers: [Teacher]! @relation(name: "teacher_assignments")
  students: [Student]! @relation(name: "student_readings")
  # tokens: TokenMap TODO Tokenize the scraped article
}

type Teacher {
  students: [Student]! @relation(name: "assigned_to")
  firstName: String!
  lastName: String!
  email: String!
  readings: [Reading]! @relation(name: "teacher_assignments")
}

type Student {
  readings: [Reading]! @relation(name: "student_readings")
  teachers: [Teacher]! @relation(name: "assigned_to")
  firstName: String!
  lastName: String!
  email: String!
}
